### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by nopnop2002** [comment]
Commenting out is required for ESP-IDF V5.0 and above

**Comment by Wolf3s** [comment]
> Commenting out is required for ESP-IDF V5.0 and above
So it wouldn´t work otherwise.

**Comment by Wolf3s** [comment]
Also, i´ve update the libsmb2 and nowadays the esp-idf V5.0 random code is on another place.

**Comment by nopnop2002** [comment]
> i´ve update the libsmb2

I did not know that.


I used the latest version of libsmb2.

I got the following error.

```
/home/nop/rtos/esp-idf-smb-camera_20240109/components/libsmb2/lib/compat.h:372:5: error: conflicting types for 'random'; have 'int(void)'
  372 | int random(void);
      |     ^~~~~~
In file included from /home/nop/rtos/esp-idf-smb-camera_20240109/components/libsmb2/lib/smb2-data-file-info.c:31:
/home/nop/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:270:9: note: previous declaration of 'random' with type 'long int(void)'
  270 | long    random (void);
```


My Environment is 
```
$ idf.py --version
ESP-IDF v5.1.2-dirty
```

**Comment by Wolf3s** [comment]
> > i´ve update the libsmb2
> 
> I did not know that.
> 
> I used the latest version of libsmb2.
> 
> I got the following error.
> 
> ```
> /home/nop/rtos/esp-idf-smb-camera_20240109/components/libsmb2/lib/compat.h:372:5: error: conflicting types for 'random'; have 'int(void)'
>   372 | int random(void);
>       |     ^~~~~~
> In file included from /home/nop/rtos/esp-idf-smb-camera_20240109/components/libsmb2/lib/smb2-data-file-info.c:31:
> /home/nop/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:270:9: note: previous declaration of 'random' with type 'long int(void)'
>   270 | long    random (void);
> ```
> 
> My Environment is
> 
> ```
> $ idf.py --version
> ESP-IDF v5.1.2-dirty
> ```

I basicly added NEED_RANDOM to the repository.

**Comment by Wolf3s** [comment]
Well i will see if i can do about it.

**Comment by nopnop2002** [comment]
For esp-idf v5.0 and later, the following operations are required:
```
git clone -b v4.0.0 https://github.com/sahlberg/libsmb2 components/libsmb2
vi components/libsmb2/lib/smb3-seal.c

---------------------------------------------------------------
#ifdef ESP_PLATFORM
#include <esp_system.h>
#include <sys/types.h>
//#define random esp_random ---> Remove this
#endif
---------------------------------------------------------------
```

**Comment by Wolf3s** [comment]
> For esp-idf v5.0 and later, the following operations are required:
> 
> ```
> git clone -b v4.0.0 https://github.com/sahlberg/libsmb2 components/libsmb2
> vi components/libsmb2/lib/smb3-seal.c
> 
> ---------------------------------------------------------------
> #ifdef ESP_PLATFORM
> #include <esp_system.h>
> #include <sys/types.h>
> //#define random esp_random ---> Remove this
> #endif
> ---------------------------------------------------------------
> ```

I've found something intersting: 

> For esp-idf v5.0 and later, the following operations are required:
> 
> ```
> git clone -b v4.0.0 https://github.com/sahlberg/libsmb2 components/libsmb2
> vi components/libsmb2/lib/smb3-seal.c
> 
> ---------------------------------------------------------------
> #ifdef ESP_PLATFORM
> #include <esp_system.h>
> #include <sys/types.h>
> //#define random esp_random ---> Remove this
> #endif
> ---------------------------------------------------------------
> ```

Well i think i figured out how to solve this: https://docs.espressif.com/projects/esp-idf/en/v5.1.2/esp32/api-reference/system/misc_system_api.html?highlight=esp_idf_version_major

**Comment by nopnop2002** [comment]
Please let me know if you find how to build correctly with the latest libsmb2 and ESP-IDF V5.x.

**Comment by Wolf3s** [comment]
> //#define random esp_random ---> Remove this

ok.

**Comment by Wolf3s** [comment]
@nopnop2002 https://github.com/sahlberg/libsmb2/pull/308

**Comment by Wolf3s** [comment]
Also test this branch here: https://github.com/Wolf3s/libsmb2/tree/esp-idf

**Comment by Wolf3s** [comment]
i´ve tested here and works fine.

**Comment by Wolf3s** [comment]
Update sahlberg has merged it.

**Comment by Wolf3s** [comment]
https://github.com/sahlberg/libsmb2

**Comment by nopnop2002** [comment]
I used the latest sahlberg/libsmb2.
This error occurred with ESP-IDF V4.4.
```
In file included from /home/nop/rtos/esp-idf-smb-camera/components/libsmb2/lib/dcerpc.c:61:
/home/nop/rtos/esp-idf-smb-camera/components/libsmb2/lib/compat.h:442:5: error: conflicting types for 'random'
 int random(void);
     ^~~~~~
In file included from /home/nop/rtos/esp-idf-smb-camera/components/libsmb2/lib/dcerpc.c:31:
/home/nop/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:270:6: note: previous declaration of 'random' was here
 long random (void);
      ^~~~~~
/home/nop/rtos/esp-idf-smb-camera/components/libsmb2/lib/dcerpc.c:89:1: warning: missing initializer for field 'vers_minor' of 'p_syntax_id_t' {aka 'struct p_syntax_id'} [-Wmissing-field-initializers]
 };
 ^
In file included from /home/nop/rtos/esp-idf-smb-camera/components/libsmb2/lib/dcerpc.c:65:
/home/nop/rtos/esp-idf-smb-camera/components/libsmb2/include/smb2/libsmb2-dcerpc.h:58:18: note: 'vers_minor' declared here
         uint16_t vers_minor;
                  ^~~~~~~~~~
/home/nop/rtos/esp-idf-smb-camera/components/libsmb2/lib/dcerpc.c:93:1: warning: missing initializer for field 'vers_minor' of 'p_syntax_id_t' {aka 'struct p_syntax_id'} [-Wmissing-field-initializers]
 };
 ^
In file included from /home/nop/rtos/esp-idf-smb-camera/components/libsmb2/lib/dcerpc.c:65:
/home/nop/rtos/esp-idf-smb-camera/components/libsmb2/include/smb2/libsmb2-dcerpc.h:58:18: note: 'vers_minor' declared here
         uint16_t vers_minor;
                  ^~~~~~~~~~
cc1: warning: unrecognized command line option '-Wno-array-parameter'
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```

**Comment by nopnop2002** [comment]
I used the latest sahlberg/libsmb2.
This error occurred with ESP-IDF V5.1.
```
/home/nop/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld: /home/nop/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/lib/esp32-psram/no-rtti/libc.a(lib_a-random.o): in function `srandom':
/builds/idf/crosstool-NG/.build/xtensa-esp32-elf/src/newlib/newlib/libc/stdlib/random.c:61: multiple definition of `srandom'; esp-idf/libsmb2/lib..a(compat.c.obj):/home/nop/rtos/esp-idf-smb-camera/components/libsmb2/lib/compat.c:294: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by nopnop2002** [comment]
From the above results, I changed lib/compat.c:
```
#ifdef ESP_PLATFORM
#include <errno.h>
#define NEED_GETLOGIN_R
//#if ESP_IDF_VERSION_MAJOR <= 4
//#define NEED_RANDOM
//#endif
//#define NEED_SRANDOM ---> 
#define login_num ENXIO
//#if ESP_IDF_VERSION_MAJOR <= 4
#define smb2_random esp_random
//#endif
#define smb2_srandom(seed)
#endif
```

And I changed lib/compat.h:
```
#ifdef ESP_PLATFORM
#include <stddef.h>
#include <esp_system.h>
#include <sys/types.h>
//#include <esp_idf_version.h>
void srandom(unsigned int seed);
//#if ESP_IDF_VERSION_MAJOR <= 4
//int random(void);
long random(void);
//#endif
int getlogin_r(char *buf, size_t size);
#endif
```

In both V4.4.5 and V5.X, rand() and srandom() are built-in functions.


Using ESP-IDF V4.4.5 ---> OK.

Using ESP-IDF V5.0.5 ---> OK.

Using ESP-IDF V5.1.2 ---> OK.

Using ESP-IDF V5.2-beta1 ---> OK.

**Comment by nopnop2002** [comment]
The following structures are defined.
```
typedef struct p_syntax_id {
        dcerpc_uuid_t uuid;
        uint16_t vers;
        uint16_t vers_minor;
} p_syntax_id_t;
```
p_syntax_id_t has three member variables.

Here we are initializing this structure, but one member variable is missing.
```
p_syntax_id_t ndr32_syntax = {
        {NDR32_UUID}, 2
};

p_syntax_id_t ndr64_syntax = {
        {NDR64_UUID}, 1
};
```

**Comment by Wolf3s** [comment]
> From the above results, I changed lib/compat.c:
> 
> ```
> #ifdef ESP_PLATFORM
> #include <errno.h>
> #define NEED_GETLOGIN_R
> //#if ESP_IDF_VERSION_MAJOR <= 4
> //#define NEED_RANDOM
> //#endif
> //#define NEED_SRANDOM ---> 
> #define login_num ENXIO
> //#if ESP_IDF_VERSION_MAJOR <= 4
> #define smb2_random esp_random
> //#endif
> #define smb2_srandom(seed)
> #endif
> ```
> 
> And I changed lib/compat.h:
> 
> ```
> #ifdef ESP_PLATFORM
> #include <stddef.h>
> #include <esp_system.h>
> #include <sys/types.h>
> //#include <esp_idf_version.h>
> void srandom(unsigned int seed);
> //#if ESP_IDF_VERSION_MAJOR <= 4
> //int random(void);
> long random(void);
> //#endif
> int getlogin_r(char *buf, size_t size);
> #endif
> ```
> 
> In both V4.4.5 and V5.X, rand() and srandom() are built-in functions.
> 
> Using ESP-IDF V4.4.5 ---> OK.
> 
> Using ESP-IDF V5.0.5 ---> OK.
> 
> Using ESP-IDF V5.1.2 ---> OK.
> 
> Using ESP-IDF V5.2-beta1 ---> OK.

Well i´ve done the changes based on your tests here: https://github.com/sahlberg/libsmb2/pull/311/files

**Comment by nopnop2002** [comment]
I tested with the latest version of libsmb2.

Everything is OK.

I've updated this.
https://github.com/nopnop2002/esp-idf-smb-camera

Thank you for your cooperation.

**Comment by Wolf3s** [comment]
> I tested with the latest version of libsmb2.
> 
> Everything is OK.
> 
> I've updated this. https://github.com/nopnop2002/esp-idf-smb-camera
> 
> thank you.

No problem, also thanks for indicate the issue itself. It was good to help you again.

**Pull request closed without merging**
